#!/bin/bash

delta=5
N1=1
N2=184

./lab4-mp $N1 2 > neo_2.txt
N=$(($N1+$delta))

while [ $N -le $N2 ]
do
./lab4-mp $N 2 >> neo_2.txt
N=$(($N+$delta))
done


./lab4-mp $N1 3 > neo_3.txt
N=$(($N1+$delta))

while [ $N -le $N2 ]
do
./lab4-mp $N 3 >> neo_3.txt
N=$(($N+$delta))
done


./lab4-mp $N1 4 > neo_4.txt
N=$(($N1+$delta))

while [ $N -le $N2 ]
do
./lab4-mp $N 4 >> neo_4.txt
N=$(($N+$delta))
done


./lab4-mp $N1 8 > neo_8.txt
N=$(($N1+$delta))

while [ $N -le $N2 ]
do
./lab4-mp $N 8 >> neo_8.txt
N=$(($N+$delta))
done

